services:
  portfolio:
    build: .
    container_name: portfolio-v2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
